trigger: none
pool: selfhosted
stages:
  - stage: terraformInit
    displayName: terraform inetialise
    jobs:
      - job: terreformInit
        displayName: Terraform Init
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'azuretoado'
            backendAzureRmResourceGroupName: 'arsh_rg'
            backendAzureRmStorageAccountName: 'arshstrg1210'
            backendAzureRmContainerName: 'lab'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
  
  - stage: terraformPlanApply    
    displayName: terraform plan apply
    dependsOn: terraformInit
    jobs : 
      - job: terraformPlanApply
        displayName: terraformPlanApply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'azuretoado'
            backendAzureRmResourceGroupName: 'arsh_rg'
            backendAzureRmStorageAccountName: 'arshstrg1210'
            backendAzureRmContainerName: 'lab'
            backendAzureRmKey: 'terraform.tfstate'
                 
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            environmentServiceNameAzureRM: 'azuretoado'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            environmentServiceNameAzureRM: 'azuretoado'
          
         