trigger: none
pool: selfhosted
stages:
  - stage: terraformInit
    displayName: INIT
    jobs:
      - job: terraformInit
        displayName: TINIT
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'azuretoado'
            backendAzureRmResourceGroupName: 'arsh_rg'
            backendAzureRmStorageAccountName: 'arshstrg1210'
            backendAzureRmContainerName: 'lab'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Dev'
            environmentServiceNameAzureRM: 'azuretoado'